# Generated by Django 5.2.1 on 2025-06-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='tunisianet_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
