# Generated by Django 5.2.1 on 2025-06-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_product_is_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_custom',
        ),
    ]
