# Generated by Django 5.2.1 on 2025-06-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_remove_product_is_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='tunisianet_password',
        ),
    ]
